INSERT INTO USERS (ID, NAME, EMAIL, HASHED_PASSWORD, CREATED_AT) VALUES (111, 'USER1', 'USER1@XXXXX.COM', 'HASHED_PASSWORD1', '2023-09-01 10:00:00');
INSERT INTO USERS (ID, NAME, EMAIL, HASHED_PASSWORD, CREATED_AT) VALUES (222, 'USER2', 'USER2@XXXXX.COM', 'HASHED_PASSWORD2', '2024-09-01 10:00:00');
INSERT INTO USERS (ID, NAME, EMAIL, HASHED_PASSWORD, CREATED_AT) VALUES (333, 'USER3', 'USER2@XXXXX.COM', 'HASHED_PASSWORD3', '2024-09-01 10:00:00');

INSERT INTO EXERCISES (ID, NAME) VALUES (111, 'Flat dumbbell chest press');
INSERT INTO EXERCISES (ID, NAME) VALUES (222, 'Incline dumbbell chest press');
INSERT INTO EXERCISES (ID, NAME) VALUES (333, 'Barbell back squat');
INSERT INTO EXERCISES (ID, NAME) VALUES (444, 'Barbell front squat');

INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('CHEST', 111);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('CHEST', 222);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('QUADS', 333);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('GLUTES', 333);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('QUADS', 444);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('GLUTES', 444);

INSERT INTO WORKOUTS (ID, DATE, NOTES, USER_ID) VALUES (111, '2023-09-01', 'RANDOM NOTES', 222);
INSERT INTO EXERCISE_SETS (ID, EXERCISE_ID, WORKOUT_ID, REPS, WEIGHT) VALUES (111, 111, 111, 10, 55.5);

INSERT INTO WORKOUTS (ID, DATE, NOTES, USER_ID) VALUES (222, '2023-09-01', 'RANDOM NOTES', 333);
INSERT INTO EXERCISE_SETS (ID, EXERCISE_ID, WORKOUT_ID, REPS, WEIGHT) VALUES (222, 111, 222, 10, 55.5);