INSERT INTO USERS (ID, NAME, EMAIL, HASHED_PASSWORD, CREATED_AT) VALUES (1, 'SYSTEM', 'SYSTEM@SYSTEM.COM', 'HASHED_PASSWORD', '2023-09-01 10:00:00');

INSERT INTO EXERCISES (ID, NAME) VALUES (111, 'Flat dumbbell chest press');
INSERT INTO EXERCISES (ID, NAME) VALUES (222, 'Incline dumbbell chest press');
INSERT INTO EXERCISES (ID, NAME) VALUES (333, 'Barbell back squat');
INSERT INTO EXERCISES (ID, NAME) VALUES (444, 'Barbell front squat');

INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('CHEST', 111);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('CHEST', 222);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('QUADS', 333);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('GLUTES', 333);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('QUADS', 444);
INSERT INTO EXERCISE_MUSCLE_GROUPS (MUSCLE_GROUPS, EXERCISE_ID) VALUES ('GLUTES', 444);
